"""
Reply engine.

The rule this module now enforces: **what the operator saves on the AI Settings
page is what the lead receives.** Previously every reply was generated by
OpenAI with the templates passed in only as a "style guide", so OpenAI
paraphrased them — editing a template changed nothing that was observable, and
the AI Chat Test never matched the saved text.

Behaviour is controlled by the `ai_mode` setting:

    templates  (default)  Saved template sent verbatim for every recognised
                          reply. OpenAI is never called.
    hybrid                Templates verbatim for the scripted steps and the
                          known objections; OpenAI only for a genuine
                          off-script question no template covers.
    ai                    OpenAI writes every reply (the old behaviour).
"""

import logging
import re
from flask import current_app

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------ #
# Settings helpers
# ------------------------------------------------------------------ #

def _s(key):
    """Load a setting from DB with fallback to DEFAULTS."""
    from models import AppSettings
    try:
        return AppSettings.get(key, AppSettings.DEFAULTS.get(key, ""))
    except Exception:
        return AppSettings.DEFAULTS.get(key, "")


def get_ai_mode() -> str:
    mode = (_s("ai_mode") or "templates").strip().lower()
    return mode if mode in ("templates", "hybrid", "ai") else "templates"


def build_vars(lead) -> dict:
    """
    The canonical placeholder values, used identically by every template, the
    OpenAI system prompt, the live webhook and the chat simulator.

    {business_name} always means the LEAD's business. {company_name} means our
    own agency. They used to be the same token, which rendered
    "I'm Sarah from {business_name}" as "I'm Sarah from Joe's Hair Studio".
    """
    lead_name = (getattr(lead, "business_name", "") or "there")
    company = _s("business_name")
    return {
        "business_name": lead_name,
        "lead_name":     lead_name,
        "company_name":  company,
        "my_company":    company,
        "agent_name":    _s("sms_agent_name"),
        "website":       _s("business_website"),
        "rating":        getattr(lead, "rating", None) or "4+",
        "reviews":       getattr(lead, "reviews_count", None) or "many",
    }


def _fill(template: str, **kwargs) -> str:
    """Replace {variable} placeholders in a template string."""
    out = template or ""
    for k, v in kwargs.items():
        out = out.replace("{" + k + "}", str(v if v is not None else ""))
    return out


def render_template_key(key: str, lead) -> str:
    """Render a saved template for a lead — verbatim apart from placeholders."""
    return _fill(_s(key), **build_vars(lead)).strip()


# ------------------------------------------------------------------ #
# Intent classification
# ------------------------------------------------------------------ #

OPT_OUT_PATTERNS = [
    r"\bstop\b", r"\bunsubscribe\b", r"\bremove me\b", r"\bopt ?-?out\b",
    r"\bdo not contact\b", r"\bdon'?t contact\b", r"\bleave me alone\b",
    r"\bremove my number\b", r"\bdon'?t text\b", r"\bstop texting\b",
    r"\bblock\b", r"\bfuck off\b", r"\bpiss off\b",
]

NUMBER_PATTERNS = [
    r"where did you get (my|this) number", r"how did you get (my|this) number",
    r"who gave you (my|this) number", r"where'?d you get (my|this) number",
    r"how do you have (my|this) number",
]

IDENTITY_PATTERNS = [
    r"who is this", r"who'?s this", r"who are you", r"who r u", r"whos this",
    r"what company", r"which company", r"what'?s this (about|regarding)",
    r"what is this (about|regarding)", r"do i know you", r"never heard of you",
    r"what do you (do|sell)", r"are you a bot", r"is this a bot", r"is this spam",
    r"is this a scam",
]

COST_PATTERNS = [
    r"how much", r"what'?s the (cost|price|catch)", r"what is the (cost|price|catch)",
    r"is it free", r"is this free", r"free\?", r"what'?s the charge",
    r"how much does it cost", r"there'?s always a catch", r"what'?s the cost",
]

POSITIVE_PATTERNS = [
    r"\byes\b", r"\byep\b", r"\byeah\b", r"\byup\b", r"\bsure\b", r"\bok\b",
    r"\bokay\b", r"\bsounds good\b", r"\bplease\b", r"\bsend it\b",
    r"\bsend me\b", r"\binterested\b", r"\bgo ahead\b", r"\bdefinitely\b",
    r"\bwhy not\b", r"\bof course\b", r"\babsolutely\b", r"\bthat'?s us\b",
    r"\bthis is\b", r"\bspeaking\b", r"\bcorrect\b", r"\bthat'?s right\b",
    r"\bshow me\b", r"\blet'?s see\b", r"\bgo on\b",
]

NEGATIVE_PATTERNS = [
    r"\bnot interested\b", r"\bno thanks\b", r"\bno thank you\b",
    r"\bdont need\b", r"\bdon'?t need\b", r"\balready have\b",
    r"\bwe have a website\b", r"\bhave a website\b", r"\bnot for me\b",
    r"\bpass\b", r"\bnope\b", r"\bnot right now\b", r"\bnot at the moment\b",
    r"\bnot the best time\b", r"\bbad time\b", r"\bwrong number\b",
    # Bare "no", but not the friendly phrases that contain it — otherwise
    # "yes, no problem" would be read as a decline.
    r"\bno\b(?!\s*(problem|worries|rush|prob\b))",
]

QUESTION_WORDS = (
    "what", "why", "how", "when", "where", "who", "which", "can you",
    "could you", "do you", "does it", "would you", "is it", "are you",
)


def _any(patterns, text) -> bool:
    return any(re.search(p, text) for p in patterns)


def classify_intent(text: str) -> str:
    """
    Map an inbound SMS to one of the intents the templates cover.

    Returns: opt_out | number | identity | cost | positive | negative | unclear
    """
    t = (text or "").lower().strip()
    if not t:
        return "unclear"

    # Order matters. "Stop texting me, not interested" is an opt-out, not a
    # decline. "How did you get my number? No thanks" is the number objection.
    if _any(OPT_OUT_PATTERNS, t):
        return "opt_out"
    if _any(NUMBER_PATTERNS, t):
        return "number"
    if _any(IDENTITY_PATTERNS, t):
        return "identity"
    if _any(COST_PATTERNS, t):
        return "cost"
    if _any(NEGATIVE_PATTERNS, t):
        return "negative"
    if _any(POSITIVE_PATTERNS, t):
        return "positive"
    return "unclear"


def _looks_like_question(text: str) -> bool:
    t = (text or "").lower().strip()
    return t.endswith("?") or t.startswith(QUESTION_WORDS)


# ------------------------------------------------------------------ #
# The conversation state machine
# ------------------------------------------------------------------ #

# Intents that answer a question without moving the lead along the script —
# the same thing a human would do: answer, then carry on where you left off.
SIDE_INTENTS = {
    "identity": "msg_who_are_you",
    "number":   "msg_number_question",
    "cost":     "msg_cost_question",
}


class Decision:
    """The outcome of one inbound message."""

    def __init__(self, template_key, status, step, intent, source="template", reply=None):
        self.template_key = template_key
        self.status = status
        self.step = step
        self.intent = intent
        self.source = source
        self.reply = reply

    def to_dict(self):
        return {
            "template_key": self.template_key,
            "status": self.status,
            "step": self.step,
            "intent": self.intent,
            "source": self.source,
            "reply": self.reply,
        }


def decide(inbound_text: str, step: int, current_status: str = "") -> Decision:
    """
    Pure state machine — no DB, no network. Given the inbound text and the step
    the lead is currently on, decide which template answers it and where the
    lead moves to.

    This single function drives the live webhook, the AI Chat Test and the Live
    Preview, so all three cannot disagree.
    """
    step = step or 0
    intent = classify_intent(inbound_text)

    if intent == "opt_out":
        return Decision("msg_opt_out", "opted_out", step, intent)

    # Questions are answered in place — the step does not advance.
    if intent in SIDE_INTENTS:
        status = current_status if current_status in ("interested",) else "replied"
        return Decision(SIDE_INTENTS[intent], status, step, intent)

    if step <= 0:
        # Opening sent; we are waiting for them to confirm we have the right business.
        if intent == "negative":
            return Decision("msg_not_interested", "not_interested", step, intent)
        return Decision("msg_compliment", "replied", 1, intent)

    if step == 1:
        # Rating + gap sent; anything that isn't a decline moves to the offer.
        if intent == "negative":
            return Decision("msg_not_interested", "not_interested", step, intent)
        return Decision("msg_offer", "replied", 2, intent)

    if step == 2:
        # The offer is on the table.
        if intent == "positive":
            return Decision("msg_interested", "interested", 3, intent)
        if intent == "negative":
            return Decision("msg_not_interested", "not_interested", step, intent)
        return Decision("msg_unclear", "replied", 2, intent)

    # step >= 3 — they already said yes. A human sends the site from here, so
    # the only thing left worth auto-answering is a decline or an opt-out.
    if intent == "negative":
        return Decision("msg_not_interested", "not_interested", step, intent)
    return Decision(None, current_status or "interested", step, intent)


# ------------------------------------------------------------------ #
# OpenAI — used for off-script questions (hybrid) or everything (ai)
# ------------------------------------------------------------------ #

def openai_available() -> bool:
    try:
        api_key = current_app.config.get("OPENAI_API_KEY", "")
    except Exception:
        return False
    return bool(api_key and str(api_key).strip().startswith("sk-"))


def _openai_reply(lead, conversation_history: list, inbound_text: str) -> str | None:
    """
    Generate a free-form SMS reply from the configured system prompt and the
    full conversation history. Returns None if OpenAI is unavailable or errors.
    """
    if not openai_available():
        logger.info("OpenAI not configured — using templates")
        return None

    try:
        api_key = current_app.config.get("OPENAI_API_KEY", "").strip()
        import openai
        client = openai.OpenAI(api_key=api_key)

        variables = build_vars(lead)
        system_prompt = _fill(_s("ai_system_prompt"), **variables)

        # Give the model the approved wording to stay close to.
        system_prompt += "\n\n--- APPROVED MESSAGE TEMPLATES (match this wording closely) ---\n"
        for label, key in (
            ("OPENING",        "msg_opening"),
            ("STEP 1",         "msg_compliment"),
            ("STEP 2 OFFER",   "msg_offer"),
            ("INTERESTED",     "msg_interested"),
            ("NOT INTERESTED", "msg_not_interested"),
            ("OPT OUT",        "msg_opt_out"),
            ("UNCLEAR",        "msg_unclear"),
            ("WHO ARE YOU",    "msg_who_are_you"),
            ("COST",           "msg_cost_question"),
            ("NUMBER",         "msg_number_question"),
        ):
            tmpl = _fill(_s(key), **variables)
            if tmpl:
                system_prompt += f"\n[{label}]\n{tmpl}\n"

        messages = [{"role": "system", "content": system_prompt}]
        for msg in (conversation_history or [])[-12:]:
            role = "assistant" if msg.get("direction") == "outbound" else "user"
            content = (msg.get("message") or "").strip()
            if content:
                messages.append({"role": role, "content": content})

        # Only append the inbound text if the history didn't already carry it —
        # otherwise the model sees the lead's last message twice.
        if not (len(messages) > 1 and messages[-1]["role"] == "user"
                and messages[-1]["content"] == (inbound_text or "").strip()):
            messages.append({"role": "user", "content": inbound_text})

        model = _s("ai_model") or "gpt-4o"
        response = client.chat.completions.create(
            model=model, messages=messages, max_tokens=200, temperature=0.75,
        )
        reply = (response.choices[0].message.content or "").strip()
        logger.info(f"OpenAI ({model}) reply for lead {getattr(lead, 'id', '?')}: '{reply[:80]}'")
        return reply or None

    except Exception as e:
        logger.warning(f"OpenAI reply failed, falling back to templates: {e}")
        return None


# ------------------------------------------------------------------ #
# Main entry point — called by the webhook handler
# ------------------------------------------------------------------ #

def resolve_reply(lead, inbound_text: str, conversation_history: list = None) -> Decision:
    """
    Full decision for one inbound message, including the rendered reply text.
    """
    step = getattr(lead, "conversation_step", 0) or 0
    status = getattr(lead, "status", "") or ""
    mode = get_ai_mode()

    d = decide(inbound_text, step, status)
    logger.info(
        f"Lead {getattr(lead, 'id', '?')} '{getattr(lead, 'business_name', '?')}' | "
        f"mode={mode} step={step} intent={d.intent} -> {d.template_key} "
        f"(status={d.status}, step={d.step}) | msg='{(inbound_text or '')[:60]}'"
    )

    # Full-AI mode: OpenAI writes everything, the state machine still tracks
    # where the lead is in the pipeline.
    if mode == "ai":
        ai = _openai_reply(lead, conversation_history, inbound_text)
        if ai:
            d.reply, d.source = ai, "openai"
            return d

    # Hybrid: OpenAI only for a genuine off-script question. Anything the
    # templates cover stays verbatim.
    elif mode == "hybrid" and d.intent == "unclear" and _looks_like_question(inbound_text):
        ai = _openai_reply(lead, conversation_history, inbound_text)
        if ai:
            d.reply, d.source = ai, "openai"
            return d

    if d.template_key:
        d.reply = render_template_key(d.template_key, lead)
        d.source = "template"
    else:
        d.reply, d.source = None, "none"
    return d


def get_next_message(lead, inbound_text: str, conversation_history: list = None):
    """Returns (reply_message, new_status, new_step)."""
    d = resolve_reply(lead, inbound_text, conversation_history)
    return d.reply, d.status, d.step


# ------------------------------------------------------------------ #
# Initial & follow-up messages
# ------------------------------------------------------------------ #

def get_initial_message(lead) -> str:
    return render_template_key("msg_opening", lead)


def get_followup_message(lead) -> str:
    count = (getattr(lead, "followup_count", 0) or 0) + 1
    key = "msg_followup_2" if count >= 2 else "msg_followup_1"
    return render_template_key(key, lead)


# ------------------------------------------------------------------ #
# AI Chat simulation (AI Chat Test page + Live Preview)
# ------------------------------------------------------------------ #

class _FakeLead:
    """Stand-in lead so the simulator runs the exact production code path."""

    def __init__(self, business_name, rating, reviews):
        self.id = 0
        self.business_name = business_name
        self.rating = rating
        self.reviews_count = reviews
        self.conversation_step = 0
        self.followup_count = 0
        self.status = "message_sent"
        self.ai_paused = False


def simulate_conversation(business_name: str, rating: float, reviews: int, messages: list) -> dict:
    """
    Replay the whole thread through the real state machine so the tester shows
    exactly what production would send — same templates, same step transitions.

    Returns a dict so the UI can show which template produced each reply and
    know when the conversation has genuinely ended.
    """
    fake = _FakeLead(business_name, rating, reviews)
    messages = messages or []

    if not any(m.get("role") == "user" for m in messages):
        return {
            "reply": get_initial_message(fake),
            "template_key": "msg_opening",
            "intent": "opening",
            "source": "template",
            "status": "message_sent",
            "step": 0,
            "ended": False,
            "mode": get_ai_mode(),
        }

    # Replay every user turn to arrive at the true current step, exactly as the
    # webhook would have advanced it message by message.
    history = []
    last = None
    for m in messages:
        text = m.get("text", "")
        if m.get("role") == "user":
            last = resolve_reply(fake, text, list(history))
            fake.status = last.status
            fake.conversation_step = last.step
            history.append({"direction": "inbound", "message": text})
            if last.reply:
                history.append({"direction": "outbound", "message": last.reply})
        else:
            history.append({"direction": "outbound", "message": text})

    if last is None:
        return {
            "reply": get_initial_message(fake), "template_key": "msg_opening",
            "intent": "opening", "source": "template", "status": "message_sent",
            "step": 0, "ended": False, "mode": get_ai_mode(),
        }

    out = last.to_dict()
    out["ended"] = last.status in ("opted_out", "not_interested") or last.reply is None
    out["mode"] = get_ai_mode()
    if not out["reply"]:
        out["reply"] = ""
    return out
